/*
 * generated by Xtext
 */
package org.xtext.example.plantext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.plantext.services.PlantExtGrammarAccess;

public class PlantExtParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PlantExtGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.plantext.parser.antlr.internal.InternalPlantExtParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.plantext.parser.antlr.internal.InternalPlantExtParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Document";
	}
	
	public PlantExtGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PlantExtGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
