/**
 * generated by Xtext
 */
package org.xtext.example.plantext.validation;

import org.xtext.example.plantext.validation.AbstractPlantExtValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PlantExtValidator extends AbstractPlantExtValidator {
}
