/*
 * generated by Xtext
 */
package org.xtext.example.plantext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.plantext.ui.internal.PlantExtActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PlantExtExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PlantExtActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PlantExtActivator.getInstance().getInjector(PlantExtActivator.ORG_XTEXT_EXAMPLE_PLANTEXT_PLANTEXT);
	}
	
}
