/*
 * generated by Xtext
 */
package org.xtext.example.plantext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PlantExtRuntimeModule extends org.xtext.example.plantext.AbstractPlantExtRuntimeModule {

}
