/*
 * generated by Xtext
 */
package org.xtext.example.plantext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PlantExtStandaloneSetup extends PlantExtStandaloneSetupGenerated{

	public static void doSetup() {
		new PlantExtStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

