/*
 * generated by Xtext
 */
package org.xtext.example.plantext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PlantExtUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.example.plantext.ui.internal.PlantExtActivator.getInstance().getInjector("org.xtext.example.plantext.PlantExt");
	}
	
}
