/*
 * generated by Xtext
 */
package org.xtext.example.plantext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PlantExtUiModule extends org.xtext.example.plantext.ui.AbstractPlantExtUiModule {
	public PlantExtUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
